// <auto-generated />
using System;
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CinemaApp.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cinemaapp.com",
                            IsAdmin = true,
                            PasswordHash = "joTvPLlCgdhD4w6AQ+b/ysBq7BqBZWsOTyAkH5sM7Rg=",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CinemaApp.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thrilling action movies",
                            Icon = "💥",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Emotional drama films",
                            Icon = "🎭",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Funny comedy films",
                            Icon = "😂",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Thriller and horror films",
                            Icon = "👻",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Science fiction films",
                            Icon = "🚀",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Romantic films",
                            Icon = "❤️",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Animated films",
                            Icon = "🎨",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Thriller films",
                            Icon = "🔪",
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cast")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ImdbRating")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1864),
                            Description = "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            GenreId = 5,
                            ImdbRating = 8.8000000000000007,
                            IsFeatured = true,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1885),
                            Description = "Batman is forced to confront the Joker, who is trying to plunge Gotham City into chaos.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            GenreId = 1,
                            ImdbRating = 9.0,
                            IsFeatured = true,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Cast = "Matthew McConaughey, Anne Hathaway, Jessica Chastain",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1889),
                            Description = "A team of astronauts travels through space searching for new habitable planets to secure the future of humanity.",
                            Director = "Christopher Nolan",
                            Duration = 169,
                            GenreId = 5,
                            ImdbRating = 8.5999999999999996,
                            IsFeatured = true,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 4,
                            Cast = "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong",
                            Country = "South Korea",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1891),
                            Description = "A poor family schemes to become employed by a wealthy household, leading to an unexpected confrontation.",
                            Director = "Bong Joon-ho",
                            Duration = 132,
                            GenreId = 2,
                            ImdbRating = 8.5999999999999996,
                            IsFeatured = false,
                            Language = "Korean",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            Title = "Parasite",
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            Cast = "Tim Robbins, Morgan Freeman, Bob Gunton",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1894),
                            Description = "A banker wrongly convicted of murder learns to survive in prison while maintaining hope for freedom.",
                            Director = "Frank Darabont",
                            Duration = 142,
                            GenreId = 2,
                            ImdbRating = 9.3000000000000007,
                            IsFeatured = true,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 6,
                            Cast = "Daveigh Chase, Suzanne Pleshette, Miyu Irino",
                            Country = "Japan",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1896),
                            Description = "Ten-year-old Chihiro becomes trapped in a spirit world and must find a way to free herself and her parents.",
                            Director = "Hayao Miyazaki",
                            Duration = 125,
                            GenreId = 7,
                            ImdbRating = 8.5999999999999996,
                            IsFeatured = false,
                            Language = "Japanese",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
                            Title = "Spirited Away",
                            Year = 2001
                        },
                        new
                        {
                            Id = 7,
                            Cast = "Daniel Kaluuya, Allison Williams, Bradley Whitford",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1899),
                            Description = "A man uncovers terrifying secrets when he visits his girlfriend's mysterious family estate.",
                            Director = "Jordan Peele",
                            Duration = 104,
                            GenreId = 4,
                            ImdbRating = 7.7000000000000002,
                            IsFeatured = false,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
                            Title = "Get Out",
                            Year = 2017
                        },
                        new
                        {
                            Id = 8,
                            Cast = "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1902),
                            Description = "The comedic adventures of a legendary hotel concierge and his young apprentice are recounted.",
                            Director = "Wes Anderson",
                            Duration = 99,
                            GenreId = 3,
                            ImdbRating = 8.0999999999999996,
                            IsFeatured = false,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
                            Title = "The Grand Budapest Hotel",
                            Year = 2014
                        },
                        new
                        {
                            Id = 9,
                            Cast = "Timothée Chalamet, Rebecca Ferguson, Oscar Isaac",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1904),
                            Description = "An epic science fiction film about the war over control of a dangerous desert planet containing a precious resource.",
                            Director = "Denis Villeneuve",
                            Duration = 155,
                            GenreId = 5,
                            ImdbRating = 8.0,
                            IsFeatured = true,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
                            Title = "Dune",
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Cast = "Ryan Gosling, Emma Stone, John Legend",
                            Country = "USA",
                            CreatedAt = new DateTime(2026, 5, 31, 19, 49, 7, 55, DateTimeKind.Local).AddTicks(1907),
                            Description = "A love story between two young dreamers chasing their ambitions in Los Angeles.",
                            Director = "Damien Chazelle",
                            Duration = 128,
                            GenreId = 6,
                            ImdbRating = 8.0,
                            IsFeatured = false,
                            Language = "English",
                            PosterUrl = "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
                            Title = "La La Land",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Mind-blowing, an incredible film!",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Rating = 9,
                            ReviewerName = "Ahmet K."
                        },
                        new
                        {
                            Id = 2,
                            Content = "One of Nolan's masterpieces.",
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Rating = 10,
                            ReviewerName = "Elif Y."
                        },
                        new
                        {
                            Id = 3,
                            Content = "Heath Ledger's Joker performance was unbelievable.",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Rating = 10,
                            ReviewerName = "Mehmet A."
                        },
                        new
                        {
                            Id = 4,
                            Content = "The visual effects are incredibly impressive.",
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Rating = 8,
                            ReviewerName = "Zeynep T."
                        },
                        new
                        {
                            Id = 5,
                            Content = "The greatest film of all time.",
                            CreatedAt = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 5,
                            Rating = 10,
                            ReviewerName = "Ali R."
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Favorite", b =>
                {
                    b.HasOne("CinemaApp.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Models.AppUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaApp.Models.Movie", b =>
                {
                    b.HasOne("CinemaApp.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CinemaApp.Models.Review", b =>
                {
                    b.HasOne("CinemaApp.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaApp.Models.AppUser", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("CinemaApp.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaApp.Models.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
